---
abstract: "Ingy's Module::Package Plugins"
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Package::Ingy
name: Module-Package-Ingy
no_index:
  directory:
    - inc
    - t
requires:
  Capture::Tiny: 0.10
  IO::All: 0.41
  Module::Install::AckXXX: 0.16
  Module::Install::AutoLicense: 0.08
  Module::Install::GithubMeta: 0.10
  Module::Install::ReadmeFromPod: 0.12
  Module::Install::RequiresList: 0.10
  Module::Install::Stardoc: 0.13
  Module::Install::VersionCheck: 0.14
  Module::Package: 0.22
  YAML::XS: 0.35
  perl: 5.8.3
resources:
  homepage: http://github.com/ingydotnet/module-package-ingy-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/module-package-ingy-pm.git
version: 0.12
